name: Go CI / CD

on:
  pull_request:
    branches:
      - test

jobs:
  Run-Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          echo "Build START" 
          go build -v ./...
        
      - name: Test
        run: |
          echo "Test START"
          go test -v ./...

      



